version: '3.8'

services:
  backend:
    image: petermwenda/yolo-backend:v1.0.0
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/yolodb
    depends_on:
      - mongo
    networks:
      - yolo-net

  client:
    image: petermwenda/yolo-client:v1.0.0
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - yolo-net

  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - yolo-net

volumes:
  mongo-data:

networks:
  yolo-net:
