---
- name: Provision YOLO E-commerce App
  hosts: all
  become: true

  tasks:
    - name: Update APT package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg', 'lsb-release']
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Install Docker
      apt:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: latest
        update_cache: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Copy project files
      synchronize:
        src: "{{ playbook_dir }}/"
        dest: /home/vagrant/yolo
        recursive: yes
        delete: no
        rsync_opts:
          - "--exclude=.git"

    - name: Run docker-compose up
      command: docker-compose up --build -d
      args:
        chdir: /home/vagrant/yolo
